name: themes
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.4.0
  provider: ^6.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  get_it:
  injectable:
  dependency_injection:
    path: ../dependency-injection/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  injectable_generator: ^1.5.3

flutter:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins_Regular.ttf
          weight: 400
        - asset: assets/font/Poppins_Black.ttf
          weight: 900
        - asset: assets/font/Poppins_Bold.ttf
          weight: 700
        - asset: assets/font/Poppins_ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins_SemiBold.ttf
          weight: 600