name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  get_it:
  injectable:
  dependency_injection:
    path: ../../dependency-injection/
  dartz: ^0.10.1
  shared:
    path: ../shared

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  injectable_generator: ^1.5.3
  build_runner: ^2.2.0